version: "3.2"
services:
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: 'sls-elasticmq'
    ports:
        - 9324:9324
        - 9325:9325
    volumes:
        - ./elasticmq.conf:/opt/elasticmq.conf
    networks:
        - hscommissions
  
  redis:
    image: redis
    ports:
      - $REDIS_PORT:$REDIS_PORT
    networks:
      - hscommissions

networks:
  hscommissions:
    driver: bridge
