version: "3.2"
services:
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: 'sls-elasticmq'
    ports:
        - 9324:9324
        - 9325:9325
    volumes:
        - ./elasticmq.conf:/opt/elasticmq.conf
    networks:
        - hscommissions

  db:
    image: mysql:latest
    env_file: ./.env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      MYSQL_DATABASE: $RDS_DATABASE
      MYSQL_USER: $RDS_USERNAME
      MYSQL_PASSWORD: $RDS_PASSWORD
      MYSQL_TCP_PORT: $RDS_PORT
    ports:
      - $RDS_PORT:$RDS_PORT
    logging:
      driver: none
    networks:
      - hscommissions
  
  redis:
    image: redis
    ports:
      - $REDIS_PORT:$REDIS_PORT
    networks:
      - hscommissions

networks:
  hscommissions:
    driver: bridge
